import pc from "picocolors";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { spawn } from "node:child_process";
import { readActiveEpic } from "../protocol/state.js";
import { epicDir } from "../protocol/paths.js";
import { AdapterSchema, type AdapterName, type EpicState } from "../protocol/schema.js";

type ExportOptions = {
  adapter?: string;
  path?: string;
  command?: string;
  ifAwaitingApproval?: boolean;
  ifPlanned?: boolean;
  quiet?: boolean;
};

export function defaultPlanMirrorPath(cwd: string, adapter: AdapterName, state: EpicState): string {
  switch (adapter) {
    case "claude":
    case "claude-code":
      return join(homedir(), ".claude", "plans", `${state.epic_id}.md`);
    case "cursor":
      return join(cwd, ".cursor", "plans", `${state.epic_id}.md`);
    case "kiro":
      return join(cwd, ".kiro", "specs", state.epic_id, "plan.md");
    case "antigravity":
      return join(cwd, ".antigravity", "plans", `${state.epic_id}.md`);
    default:
      return join(cwd, ".atelier", "exports", adapter, `${state.epic_id}.md`);
  }
}

export function expandPlanPath(template: string, cwd: string, state: EpicState): string {
  const home = homedir();
  const expanded = template.startsWith("~/")
    ? join(home, template.slice(2))
    : template;
  return expanded
    .replaceAll("{cwd}", cwd)
    .replaceAll("{home}", home)
    .replaceAll("{epic_id}", state.epic_id)
    .replaceAll("{title}", state.title);
}

function renderNativePlan(state: EpicState, plan: string): string {
  const source = `.atelier/epics/${state.epic_id}/plan.md`;
  return [
    `<!-- Generated by atelier-kit from ${source}. Do not treat this mirror as the source of truth. -->`,
    "",
    plan.trimEnd(),
    "",
  ].join("\n");
}

async function runExternalCommand(command: string, env: NodeJS.ProcessEnv): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const child = spawn(command, {
      env,
      shell: true,
      stdio: "inherit",
    });
    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Export command failed with exit code ${code}`));
      }
    });
  });
}

export async function exportActivePlan(
  cwd: string,
  opts: ExportOptions = {},
): Promise<{ path: string; skipped: boolean }> {
  const adapter = AdapterSchema.parse(opts.adapter ?? "generic");
  const { state } = await readActiveEpic(cwd);
  if (!state) {
    throw new Error("No active Atelier epic.");
  }
  if ((opts.ifAwaitingApproval || opts.ifPlanned) && state.status !== "planned") {
    return { path: "", skipped: true };
  }

  const sourcePath = join(epicDir(cwd, state.epic_id), "plan.md");
  const plan = await readFile(sourcePath, "utf8");
  const targetPath = opts.path
    ? expandPlanPath(opts.path, cwd, state)
    : defaultPlanMirrorPath(cwd, adapter, state);

  await mkdir(dirname(targetPath), { recursive: true });
  await writeFile(targetPath, renderNativePlan(state, plan), "utf8");

  if (opts.command) {
    await runExternalCommand(opts.command, {
      ...process.env,
      ATELIER_ADAPTER: adapter,
      ATELIER_EPIC_ID: state.epic_id,
      ATELIER_PLAN_SOURCE: sourcePath,
      ATELIER_PLAN_PATH: targetPath,
      ATELIER_PROJECT_DIR: cwd,
    });
  }

  return { path: targetPath, skipped: false };
}

export async function cmdExportPlan(cwd: string, opts: ExportOptions = {}): Promise<void> {
  try {
    const result = await exportActivePlan(cwd, opts);
    if (result.skipped) {
      if (!opts.quiet) {
        console.log(pc.dim("No export: active epic is not planned."));
      }
      return;
    }
    if (!opts.quiet) {
      console.log(pc.green(`Exported active Atelier plan: ${result.path}`));
    }
  } catch (error) {
    console.error(pc.red((error as Error).message));
    process.exitCode = 1;
  }
}
